apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  annotations:
    name: {{ .Values.app_name }}
  labels:
    app: {{ .Values.app_name }}
spec:
  ports:
      {{- toYaml .Values.servicePort | nindent 4 }}
  selector:
    app: {{ .Values.app_name }}